name: Test Rust crate on illumos!
on:
    push:
        paths-ignore:
            - '**.md'
        branches:
            - main

jobs:
  test-on-illumos:
    name: illumos test with rust
    runs-on: macos-latest
    strategy:
      matrix:
        target: ["x86_64-unknown-illumos"]
    steps:
    - uses: actions/checkout@master
    - name: Run check
      uses: papertigers/illumos-vm@main
      with:
        mem: 7168
        prepare: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
        run: |
          set path=($HOME/.cargo/bin $path)
          cargo install cargo-hack
          cargo hack test --feature-powerset --target ${{ matrix.target }}
          cargo hack test --feature-powerset --release --target ${{ matrix.target }}
