name: Test Rust crate on illumos!
on:
    push:
        paths-ignore:
            - '**.md'
        branches:
            - main

jobs:
  test-on-illumos:
    name: illumos test with rust
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Run check
      uses: papertigers/illumos-vm@main
      with:
        mem: 7168
        prepare: |
          pkg install build-essential
          curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal
        run: |
          source "$HOME/.cargo/env"
          cargo test
